# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: extract-papers

on:
  schedule:
  # Run at 0 minutes past 12th hour
    - cron:  '0 */12 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  extract-papers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Extract HDR UK Papers
        run: python3 paper-extractor.py
      - name: Extract COVID-19 Preprints
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secrets/contacts.csv data/contacts.csv.gpg
          python3 preprint-extractor.py
      - name: Commit extracts to master branch
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Commit new papers and preprints
          branch: ${{ github.head_ref }}
          commit_user_name: Susheel Varma
          commit_user_email: susheel.varma@hdruk.ac.uk
          commit_author: Susheel Varma <susheel.varma@hdruk.ac.uk>
      - name: Commit extracts to gh-pages branch
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Commit new papers and preprints
          branch: gh-pages
          commit_user_name: Susheel Varma
          commit_user_email: susheel.varma@hdruk.ac.uk
          commit_author: Susheel Varma <susheel.varma@hdruk.ac.uk>
